sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

env:
  - magento=2.0.5
  - magento=2.0.8
  - magento=2.0.15
  - magento=2.1.1
  - magento=2.1.6
  - magento=2.1.7
  - magento=2.1.8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cd $HOME
#  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY
  - chmod +x $HOME/*
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  # install magento to home directory
  - cd $HOME
#  - composer create-project "magento/community-edition:$magento" ce

  # install cobby
#  - cd ce
  - composer require slavkodick/cobby:dev-master
  - cd vendor

  # update cs and standards
  - composer require squizlabs/php_codesniffer:*
  - composer require magento-ecg/coding-standard:*

  - composer update

script:
  # run phpcs
  - cd $HOME/ce/vendor
  - ./bin/phpcs --standard=./magento-ecg/coding-standard/EcgM2/ --warning-severity=6 ./slavkodick/cobby/
 